package com.mycompany.airlineticketingsystem.service;

import com.mycompany.airlineticketingsystem.config.DatabaseConnection;
import com.mycompany.airlineticketingsystem.enums.Gender;
import com.mycompany.airlineticketingsystem.model.Booking;
import com.mycompany.airlineticketingsystem.model.Flight;
import com.mycompany.airlineticketingsystem.model.Plane;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

public class BookingServiceTest {

    private BookingService bookingService;
    private FlightService flightService;
    
    // Test Data Identifiers
    private String testFlightId;
    private String testIcNo;
    private String testBookingId;
    private static final String TEST_PLANE_ID = "TP_TEST"; 

    @BeforeEach
    public void setUp() {
        bookingService = new BookingServiceImpl();
        flightService = new FlightServiceImpl();
        
        // 1. Generate Unique IDs
        testFlightId = "TF" + (System.currentTimeMillis() % 100000); 
        testIcNo = "IC" + (System.currentTimeMillis() % 100000);
        
        System.out.println("Setting up Test Data | Flight: " + testFlightId + " | Customer: " + testIcNo);

        // 2. Ensure Plane Exists (Required for Flight)
        createTestPlane();

        // 3. Create Flight (Required for Booking)
        // This also auto-generates seats (e.g., testFlightId + "-1A")
        createTestFlight();

        // 4. Create Customer (Required for Booking FK)
        createTestCustomer();
    }

    @Test
    public void testGenerateNewBookingId() {
        String id = bookingService.generateNewBookingId();
        Assertions.assertNotNull(id);
        Assertions.assertTrue(id.startsWith("B"), "Booking ID should start with 'B'");
    }

    @Test
    public void testSaveBooking() {
        // 1. Prepare Booking Object
        Booking booking = new Booking();
        testBookingId = bookingService.generateNewBookingId() + "_TEST"; // Unique ID
        
        booking.setBookingId(testBookingId);
        booking.setFlightId(testFlightId);      // Must exist in DB
        booking.setIcNo(testIcNo);              // Must exist in DB (Customer)
        booking.setStatus("CONFIRMED");
        booking.setBookingDate(LocalDateTime.now());
        
        // IMPORTANT: Seat ID must match the format generated by FlightService
        // Format is usually: FLIGHT_ID + "-" + SEAT_NUMBER
        booking.setSeatId(testFlightId + "-1A"); 
        
        booking.setTotalPrice(new BigDecimal("100.00"));

        // 2. Execute & Verify
        assertDoesNotThrow(() -> bookingService.saveBooking(booking), 
            "Saving booking should succeed with valid Foreign Keys");
    }

    @AfterEach
    public void tearDown() {
        System.out.println("Cleaning up Test Data...");
        
        // Delete in order to respect Foreign Keys
        // Booking -> Seat (update status) -> Flight -> Plane
        // Booking -> Customer
        
        deleteBooking(testBookingId);
        
        // Delete Flight (This usually cascades/deletes seats in logic)
        flightService.deleteFlight(testFlightId);
        
        deleteCustomer(testIcNo);
        deletePlane(TEST_PLANE_ID);
    }

    // --- HELPER METHODS ---

    private void createTestPlane() {
        String sql = "INSERT INTO plane (plane_id, model, capacity) VALUES (?, ?, ?) ON CONFLICT (plane_id) DO NOTHING";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, TEST_PLANE_ID);
            stmt.setString(2, "TestJet");
            stmt.setInt(3, 4); 
            stmt.executeUpdate();
        } catch (Exception e) { e.printStackTrace(); }
    }

    private void createTestFlight() {
        Plane plane = new Plane(TEST_PLANE_ID, "TestJet", 4);
        Flight flight = new Flight.Builder()
                .id(testFlightId)
                .route("TestOrigin", "TestDest")
                .timing(LocalDateTime.now().plusDays(1), LocalDateTime.now().plusDays(1).plusHours(2))
                .prices(100.0, 200.0)
                .plane(plane.getPlaneId()) 
                .build();
        
        // This service method generates the seats automatically
        try {
            flightService.createFlight(flight, plane);
        } catch (Exception e) {
            Assertions.fail("Failed to create test flight: " + e.getMessage());
        }
    }

    private void createTestCustomer() {
        String sql = "INSERT INTO customer (ic_no, name, email, phone_number, gender, password) VALUES (?, ?, ?, ?, ?, ?)";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, testIcNo);
            stmt.setString(2, "Test User");
            stmt.setString(3, "test@test.com");
            stmt.setString(4, "0123456789");
            stmt.setString(5, Gender.MALE.name());
            stmt.setString(6, "password");
            stmt.executeUpdate();
        } catch (Exception e) { 
            Assertions.fail("Failed to create test customer: " + e.getMessage());
        }
    }

    private void deleteBooking(String bookingId) {
        if (bookingId == null) return;
        String sql = "DELETE FROM booking WHERE booking_id = ?";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, bookingId);
            stmt.executeUpdate();
        } catch (Exception e) { e.printStackTrace(); }
    }

    private void deleteCustomer(String icNo) {
        String sql = "DELETE FROM customer WHERE ic_no = ?";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, icNo);
            stmt.executeUpdate();
        } catch (Exception e) { e.printStackTrace(); }
    }
    
    private void deletePlane(String planeId) {
        String sql = "DELETE FROM plane WHERE plane_id = ?";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, planeId);
            stmt.executeUpdate();
        } catch (Exception e) { e.printStackTrace(); }
    }
}
